---
area/bootstrap:
  - changed-files:
      - any-glob-to-any-file:
          - kubernetes/bootstrap/**/*

area/talos:
  - changed-files:
      - any-glob-to-any-file:
          - kubernetes/talos/**/*

area/kubernetes:
  - changed-files:
      - any-glob-to-any-file:
          - kubernetes/**/*

area/docker:
  - changed-files:
      - any-glob-to-any-file:
          - ansible/services/*

area/terraform:
  - changed-files:
      - any-glob-to-any-file:
          - terraform/**/*

area/github:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*

area/renovate:
  - changed-files:
      - any-glob-to-any-file:
          - .renovate/**/*
          - .renovaterc.json5
