---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  core: .taskfiles/core.yml
  secrets: .taskfiles/secrets
  talos:
    taskfile: kubernetes/talos
    dir: kubernetes/talos

tasks:
  default:
    desc: List tasks
    cmds:
      - task --list-all
