---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  ANSIBLE_DIR: "{{.ROOT_DIR}}/ansible"
  TERRAFORM_DIR: "{{.ROOT_DIR}}/terraform"
  K8S_DIR: "{{.ROOT_DIR}}/kubernetes"
  TALOS_DIR: "{{.ROOT_DIR}}/kubernetes/talos"
  PRIVATE_DIR: "{{.ROOT_DIR}}/.private"
  TEMP_DIR: "{{.ROOT_DIR}}/.temp"
  CACHE_DIR: "{{.ROOT_DIR}}/.cache"

includes:
  core: .taskfiles/core.yml
  secrets: .taskfiles/secrets
  k8s:
    taskfile: kubernetes/
    dir: kubernetes/

tasks:
  default:
    desc: List tasks
    cmds:
      - task --list-all
