---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  infra: { taskfile: infra.yml, flatten: true }
  k8s: { taskfile: k8s.yml, flatten: true }
  media: { taskfile: media.yml, flatten: true }
  services: { taskfile: services.yml, flatten: true }

vars:
  VAULT_CMD: vault kv put
  PATH: ops

tasks:
  create:*:
    desc: Create Vault secret [SECRET-NAME]
    deps: [bw-unlock, bw-sync]
    vars:
      SECRET: "{{index .MATCH 0}}"
    cmds:
      - echo "Creating secret for {{.SECRET}}"
      - task: secret-{{.SECRET}}

  get:*:*:
    desc: Get Bitwarden secret [ITEM:SECRET-NAME]
    deps: [bw-unlock, bw-sync]
    silent: true
    vars:
      ITEM: "{{index .MATCH 0}}"
      SECRET: "{{index .MATCH 1}}"
    cmds:
      - |
        if [[ "{{.SECRET}}" == "username" || "{{.SECRET}}" == "password" ]]; then
          bww get {{.SECRET}} {{.ITEM}}
        else
          bwget {{.ITEM}} {{.SECRET}}
        fi

  list:
    desc: List all secret tasks
    silent: true
    cmd: yq '.tasks | keys | .[] | select(. == "secret-*") | sub("^secret-"; "")' {{.TASKFILE_DIR}}/*

  bw-unlock:
    internal: true
    run: once
    cmds:
      - bwunlock
    status:
      - test $(bww status 2> /dev/null | jq -r '.status') == "unlocked"

  bw-sync:
    desc: Sync Bitwarden vault (cached for 10 minutes)
    internal: true
    run: once
    silent: true
    vars:
      SYNC_MARKER: "{{.ROOT_DIR}}/.cache/bw-last-sync"
    status:
      # Skip if sync marker exists and is newer than 10 minutes (600 seconds)
      - test -f {{.SYNC_MARKER}} && test $(( $(date +%s) - $(stat -f %m {{.SYNC_MARKER}}) )) -lt 600
    cmds:
      - mkdir -p {{.ROOT_DIR}}/.cache
      - |
        echo "Syncing Bitwarden vault..."
        bww sync > /dev/null
        touch {{.SYNC_MARKER}}
        echo "✓ Bitwarden vault synced"

  vault:
    internal: true
    cmd: "vault kv put {{.PATH}} {{.SECRET}}"
    requires:
      vars: [PATH, SECRET]
    prompt:
      - |-
        Creating vault secret in {{.PATH}}:
        ---
        {{.SECRET}}
        ---
        Continue?

  save:
    internal: true
    cmd: 'echo "{{.VALUE}}" > "{{.OUTPUT}}"'
    requires:
      vars: [VALUE, OUTPUT]
    prompt:
      - |-
        Value:
        ---
        {{.VALUE}}
        ---
        Outputfile: {{.OUTPUT}}
        Continue?

  refresh:
    desc: Refresh external secrets
    cmd: |
      kubectl get externalsecret -A --no-headers -o custom-columns="NAMESPACE:.metadata.namespace,NAME:.metadata.name" |
        while read ns name; do kubectl annotate externalsecret "$name" -n "$ns" force-sync=$(date +%s) --overwrite; done

  vault:token:
    desc: Generate new admin token
    cmd: |
      VAULT_TOKEN=$(jq -r '.root_token' < {{.INIT_FILE}}) vault token create -policy=admin -format=json > {{.ADMIN_TOKEN_FILE}}
      token=$(jq -r '.auth.client_token' < {{.ADMIN_TOKEN_FILE}})
      command -v gsed &>/dev/null && cmd=gsed || cmd=sed
      $cmd -i "/^VAULT_TOKEN=/d" "{{.ENV_FILE}}"
      $cmd -i "\$aVAULT_TOKEN=$token" "{{.ENV_FILE}}"
    vars:
      INIT_FILE: "{{.PRIVATE_DIR}}/vault/vault-init.json"
      ADMIN_TOKEN_FILE: "{{.PRIVATE_DIR}}/vault/admin-token.json"
      ENV_FILE: "{{.PRIVATE_DIR}}/env.d/vault.env"
    preconditions:
      - test -f "{{.INIT_FILE}}"
      - test -f "{{.ADMIN_TOKEN_FILE}}"
      - test -f "{{.ENV_FILE}}"
