---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  infra: { taskfile: infra.yml, flatten: true }
  k8s: { taskfile: k8s.yml, flatten: true }
  media: { taskfile: media.yml, flatten: true }
  services: { taskfile: services.yml, flatten: true }

vars:
  VAULT_CMD: vault kv put
  PATH: ops

tasks:
  create:*:
    desc: Create Vault secret (task secrets:create:[secret-name])
    deps: [bw-unlock]
    vars:
      SECRET: "{{index .MATCH 0}}"
    cmds:
      - echo "Creating secret for {{.SECRET}}"
      - task: secret-{{.SECRET}}

  list:
    desc: List all secret tasks
    silent: true
    cmd: yq '.tasks | keys | .[] | select(. == "secret-*") | sub("^secret-"; "")' {{.TASKFILE_DIR}}/*

  bw-unlock:
    internal: true
    run: once
    cmds:
      - bwunlock
    status:
      - test $(bww status 2> /dev/null | jq -r '.status') == "unlocked"

  vault:
    internal: true
    cmd: "vault kv put {{.PATH}} {{.SECRET}}"
    requires:
      vars: [PATH, SECRET]
    prompt:
      - |-
        Creating vault secret in {{.PATH}}:
        ---
        {{.SECRET}}
        ---
        Continue?

  save:
    internal: true
    cmd: 'echo "{{.VALUE}}" > "{{.OUTPUT}}"'
    requires:
      vars: [VALUE, OUTPUT]
    prompt:
      - |-
        Value:
        ---
        {{.VALUE}}
        ---
        Outputfile: {{.OUTPUT}}
        Continue?

  refresh:
    desc: Refresh external secrets
    cmd: |
      kubectl get externalsecret -A --no-headers -o custom-columns="NAMESPACE:.metadata.namespace,NAME:.metadata.name" |
        while read ns name; do kubectl annotate externalsecret "$name" -n "$ns" force-sync=$(date +%s) --overwrite; done
